/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002019",
        outline: "#8d90a0",
        "on-secondary-container": "#ffddd2",
        "on-tertiary": "#00382d",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#2c3951",
        "primary-container": "#2563eb",
        secondary: "#ffb59d",
        background: "#041329",
        "on-primary-fixed": "#00174b",
        "surface-container-lowest": "#010e24",
        "outline-variant": "#434655",
        "tertiary-container": "#007c66",
        "on-secondary": "#5d1900",
        "on-tertiary-fixed-variant": "#005142",
        "inverse-primary": "#0053db",
        "tertiary-fixed": "#5ffbd6",
        "surface-tint": "#b4c5ff",
        "tertiary-fixed-dim": "#38debb",
        "on-primary": "#002a78",
        "on-secondary-fixed-variant": "#832600",
        "surface-container-highest": "#27354c",
        error: "#ffb4ab",
        "surface-container-high": "#1c2a41",
        "surface-dim": "#041329",
        primary: "#b4c5ff",
        "on-surface": "#d6e3ff",
        "on-primary-container": "#eeefff",
        "on-error": "#690005",
        "on-surface-variant": "#c3c6d7",
        "on-tertiary-container": "#b8ffe9",
        tertiary: "#38debb",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#233148",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59d",
        "inverse-surface": "#d6e3ff",
        surface: "#041329",
        "on-secondary-fixed": "#390c00",
        "secondary-container": "#b83900",
        "surface-container-low": "#0d1c32",
        "error-container": "#93000a",
        "on-background": "#d6e3ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-variant": "#27354c",
        "surface-container": "#112036",
        "risk-accent": "#ff8c00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        xs: "4px",
        xl: "48px",
        lg: "24px",
        md: "16px",
        base: "4px",
        gutter: "24px",
        "section-gap": "40px",
        "container-max": "1280px",
        "container-padding": "24px",
      },
      fontFamily: {
        "display-lg": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "headline-lg": ["Inter"],
        "display-lg-mobile": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
